### ISSUE TITLE
Linux - user home instead of the root home

### ISSUE THREAD

**Issue by aminya** [sindresorhus/untildify#19]
If you use untildify in a Node process started as a root, it expands to `/root/`. Is there a way to expand to a user's home instead? 

One way I can think of is to use `process.env.SUDO_USER`

**Comment by sindresorhus** [comment]
You can also [downgrade from root](https://github.com/sindresorhus/downgrade-root). I assume you're using root to be able to use port 80.

https://github.com/sindresorhus/untildify/issues/1 could be a solution for you as you could pass in `process.env.SUDO_USER`.

I don't think this package should have special handling for root. Some users might actually want the root home directory.
