### ISSUE TITLE
Should '~' be resolved?

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/untildify#3]
Right now, only `~/` gets resolved. In my shell, I can do `echo ~` and it expands my home folder correctly.

Would you agree to changing this?

**Comment by sindresorhus** [comment]
Yes

**Comment by silverwind** [comment]
The new regexp is a bit tricky, but I think it handles all cases:

```js
'~'      -> '/Users/silverwind'
'~/'     -> '/Users/silverwind/'
'~/abc'  -> '/Users/silverwind/abc'
'~\\abc' -> '/Users/silverwind\\abc'
'~abc'   -> '~abc'
```
