### ISSUE TITLE
Support for ~+, ~-, ~n

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/untildify#4]
* `~+` should expand to the output of `process.cwd()`
*  `~-` and `~n` need access to the directory stack. Probably possible through undocumented API.

Docs:
https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html
http://zsh.sourceforge.net/Doc/Release/Expansion.html#Filename-Expansion

**Comment by sindresorhus** [comment]
Does anyone actually use `~+` though? I don't think there's any point in trying to be bash compatible as that's not fully possible anyways.

**Comment by silverwind** [comment]
Did some research, and it seems node doesn't update `process.env.PWD` and `process.env.OLDPWD` on `process.chdir()`, which I think is a bug in itself, but this pretty much means `~-` and `~n` aren't implementable. Personally, I don't see much use in `~+` if we don't support the others as well.

**Comment by sindresorhus** [comment]
> Did some research, and it seems node doesn't update process.env.PWD and process.env.OLDPWD on process.chdir()

That's intentional. `process.env` represents a static version of the environment that started the node process. `process.chdir` is contained to the node process.

> Personally, I don't see much use in ~+ if we don't support the others as well.

Agreed.

-

Feel free to do the release now btw.

**Comment by silverwind** [comment]
Well, it seems that the `process.env.PWD` at least isn't a bug and that variable should only be set by the shell, according to [this](https://stackoverflow.com/questions/3642050/chdir-not-affecting-environment-variable-pwd).

Having support for just `~+` is a weak use case I'd say, because most people would probably just use `process.cwd()`.

**Comment by silverwind** [comment]
And it's released. Went as expected, but had a git warning on the final push (`warning: push.default is unset`) because I usually don't push without a branch. I'm curious - what's your `push.default` setting in git?

**Comment by silverwind** [comment]
To answer my own question: `push.default simple` is probably the way to go :)

**Comment by sindresorhus** [comment]
@silverwind Yeah. Upgrade to latest git ;)

**Comment by silverwind** [comment]
It's not that, It just hadn't occured to me you could push without a branch ;)

**Comment by sindresorhus** [comment]
The warning *is* caused by that: http://stackoverflow.com/questions/13148066/warning-push-default-is-unset-its-implicit-value-is-changing-in-git-2-0

**Comment by silverwind** [comment]
Yeah, but just upgrading alone doesn't squelch it, you have to explicitely set it. I've just been using `git push <remote> <branch>` since forever so it didn't pop up earlier :)
